services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=Marafone'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  postgresTests:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=Marafone_TEST'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5431:5432'
    profiles: [test]
